config/routes.rb
Rails.application.routes.draw do

  resources :groups
  resources :common_static_fields

  post "/entities/share_or_interest" => "entities#share_or_interest"
  get "/entities/xhr_list" => "entities#xhr_list"
  resources :entities

  namespace :entities do
    get "individuals/basic_info/(:entity_key)" => "individuals#basic_info", as: :individuals_basic_info
    post "individuals/basic_info/(:entity_key)" => "individuals#basic_info"
    patch "individuals/basic_info/:entity_key" => "individuals#basic_info"
    get "individuals/owns/(:entity_key)" => "individuals#owns", as: :individuals_owns
    get "corporates/basic_info/(:entity_key)" => "corporates#basic_info", as: :corporates_basic_info
    post "corporates/basic_info/(:entity_key)" => "corporates#basic_info"
    patch "corporates/basic_info/:entity_key" => "corporates#basic_info"
    get "corporates/contact_info/:entity_key" => "corporates#contact_info", as: :corporates_contact_info
    post "corporates/contact_info/:entity_key" => "corporates#contact_info"
    patch "corporates/contact_info/:entity_key" => "corporates#contact_info"
    get "corporates/directors/:entity_key/(:id)" => "corporates#directors", as: :corporates_directors
    get "corporates/director/:entity_key/(:id)" => "corporates#director", as: :corporates_director
    post "corporates/director/:entity_key/(:id)" => "corporates#director"
    patch "corporates/director/:entity_key/(:id)" => "corporates#director"
    delete "corporates/director/:id" => "corporates#director"
    get "corporates/officers/:entity_key/(:id)" => "corporates#officers", as: :corporates_officers
    get "corporates/officer/:entity_key/(:id)" => "corporates#officer", as: :corporates_officer
    post "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    patch "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    delete "corporates/officer/:id" => "corporates#officer"
    get "corporates/stockholders/:entity_key/(:id)" => "corporates#stockholders", as: :corporates_stockholders
    get "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder", as: :corporates_stockholder
    post "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    patch "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    delete "corporates/stockholder/:id" => "corporates#stockholder"
    get "corporates/owns/(:entity_key)" => "corporates#owns", as: :corporates_owns
    get "llc/basic_info/(:entity_key)" => "llc#basic_info", as: :llc_basic_info
    post "llc/basic_info/(:entity_key)" => "llc#basic_info"
    patch "llc/basic_info/:entity_key" => "llc#basic_info"
    get "llc/contact_info/:entity_key" => "llc#contact_info", as: :llc_contact_info
    post "llc/contact_info/:entity_key" => "llc#contact_info"
    patch "llc/contact_info/:entity_key" => "llc#contact_info"
    get "llc/managers/:entity_key/(:id)" => "llc#managers", as: :llc_managers
    get "llc/manager/:entity_key/(:id)" => "llc#manager", as: :llc_manager
    post "llc/manager/:entity_key/(:id)" => "llc#manager"
    patch "llc/manager/:entity_key/(:id)" => "llc#manager"
    delete "llc/manager/:id" => "llc#manager"
    get "llc/members/:entity_key/(:id)" => "llc#members", as: :llc_members
    get "llc/member/:entity_key/(:id)" => "llc#member", as: :llc_member
    post "llc/member/:entity_key/(:id)" => "llc#member"
    patch "llc/member/:entity_key/(:id)" => "llc#member"
    delete "llc/member/:id" => "llc#member"
    get "llc/owns/(:entity_key)" => "llc#owns", as: :llc_owns
    get "llp/basic_info/(:entity_key)" => "llp#basic_info", as: :llp_basic_info
    post "llp/basic_info/(:entity_key)" => "llp#basic_info"
    patch "llp/basic_info/:entity_key" => "llp#basic_info"
    get "llp/contact_info/:entity_key" => "llp#contact_info", as: :llp_contact_info
    post "llp/contact_info/:entity_key" => "llp#contact_info"
    patch "llp/contact_info/:entity_key" => "llp#contact_info"
    get "llp/partners/:entity_key/(:id)" => "llp#partners", as: :llp_partners
    get "llp/partner/:entity_key/(:id)" => "llp#partner", as: :llp_partner
    post "llp/partner/:entity_key/(:id)" => "llp#partner"
    patch "llp/partner/:entity_key/(:id)" => "llp#partner"
    delete "llp/partner/:id" => "llp#partner"
    get "llp/owns/(:entity_key)" => "llp#owns", as: :llp_owns
    get "partnership/basic_info/(:entity_key)" => "partnership#basic_info", as: :partnership_basic_info
    post "partnership/basic_info/(:entity_key)" => "partnership#basic_info"
    patch "partnership/basic_info/:entity_key" => "partnership#basic_info"
    get "partnership/contact_info/:entity_key" => "partnership#contact_info", as: :partnership_contact_info
    post "partnership/contact_info/:entity_key" => "partnership#contact_info"
    patch "partnership/contact_info/:entity_key" => "partnership#contact_info"
    get "partnership/partners/:entity_key/(:id)" => "partnership#partners", as: :partnership_partners
    get "partnership/partner/:entity_key/(:id)" => "partnership#partner", as: :partnership_partner
    post "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    patch "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    delete "partnership/partner/:id" => "partnership#partner"
    get "partnership/owns/(:entity_key)" => "partnership#owns", as: :partnership_owns
    get "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info", as: :limited_partnership_basic_info
    post "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info"
    patch "limited_partnership/basic_info/:entity_key" => "limited_partnership#basic_info"
    get "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info", as: :limited_partnership_contact_info
    post "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    patch "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    get "limited_partnership/limited_partners/:entity_key/(:id)" => "limited_partnership#limited_partners", as: :limited_partnership_limited_partners
    get "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner", as: :limited_partnership_limited_partner
    post "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    patch "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    delete "limited_partnership/limited_partner/:id" => "limited_partnership#limited_partner"
    get "limited_partnership/general_partners/:entity_key/(:id)" => "limited_partnership#general_partners", as: :limited_partnership_general_partners
    get "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner", as: :limited_partnership_general_partner
    post "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    patch "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    delete "limited_partnership/general_partner/:id" => "limited_partnership#general_partner"
    get "limited_partnership/owns/(:entity_key)" => "limited_partnership#owns", as: :limited_partnership_owns
    get "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info", as: :sole_proprietorship_basic_info
    post "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info"
    patch "sole_proprietorship/basic_info/:entity_key" => "sole_proprietorship#basic_info"
    get "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info", as: :sole_proprietorship_contact_info
    post "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    patch "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    get "sole_proprietorship/owns/(:entity_key)" => "sole_proprietorship#owns", as: :sole_proprietorship_owns
    get "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info", as: :guardianship_basic_info
    post "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info"
    patch "guardianship/basic_info/:entity_key" => "guardianship#basic_info"
    get "guardianship/judge/:entity_key/(:id)" => "guardianship#judge", as: :guardianship_judge
    post "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    patch "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    delete "guardianship/judge/:id" => "guardianship#judge"
    get "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian", as: :guardianship_guardian
    post "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    patch "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    delete "guardianship/guardian/:id" => "guardianship#guardian"
    get "guardianship/ward/:entity_key/(:id)" => "guardianship#ward", as: :guardianship_ward
    post "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    patch "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    delete "guardianship/ward/:id" => "guardianship#ward"
    get "guardianship/owns/(:entity_key)" => "guardianship#owns", as: :guardianship_owns
    get "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info", as: :tenancy_in_common_basic_info
    post "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info"
    patch "tenancy_in_common/basic_info/:entity_key" => "tenancy_in_common#basic_info"
    get "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common", as: :tenancy_in_common_tenant_in_common
    post "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"
    patch "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"

app/models/Entity/agent.rb
class Agent < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Agent")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/beneficiary.rb
class Beneficiary < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "Beneficiary")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  validate :validate_my_percentage
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:beneficiary_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:beneficiary_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:beneficiary_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end

  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/director.rb
class Director < PeopleAndFirm

  belongs_to :entity

  include MyFunction

  default_scope{ where(class_name: "Director")}
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  validate :entity_presence

  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/general_partner.rb
class GeneralPartner < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "GeneralPartner")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  validate :validate_my_percentage
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:partnership_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:partnership_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f == self.total_remaining_share_or_interest
      errors.add(:partnership_interest, " can not be 100%")
      return false
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:partnership_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/guardian.rb
class Guardian < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Guardian")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/judge.rb
class Judge < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Judge")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/concerns/entity_type.rb
class EntityType < MemberType

end

app/views/entities/tenancy_in_common/_basic_info.html.slim
- if @just_created.present?
  .modal.fade#entity-creation-message tabindex="-3" role="dialog" aria-labelledby="entity-creation-message"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .corporation-creation-message
            = "Congratulations, you have created a client record for #{@entity.name}, a Tenancy in Common."
        .modal-footer
          button.btn.btn-primary.should-not-change-date-of-formation-cancel data-dismiss="modal" type="button"  Close

= form_for @entity, url: entities_tenancy_in_common_basic_info_path( @entity.key ), remote: true, html: { class: "entity-page-xhr" } do |f|
  - if @entity.errors.any?
    #error_explanation
      h2 = "#{pluralize(@entity.errors.count, "error")} prohibited this Tenancy in Common from being saved:"
      ul
        - override_active_record_errors(@entity.errors.messages, {name: :property_address, base: ''}).each do |message|
          li = message
  .col-lg-4.close-md-4.col-sm-12.col-xs-12
    - available_properties = Property.where(id: AccessResource.get_ids(resource_klass: 'Property', user: current_user), ownership_status: 'Purchased', owner_entity_id: [0, nil]).select {|s| !s.is_owned_by_concurrent_estate?}
    - if available_properties.length > 0
      .clearfix
      .form-group
        label.control-label Date of Formation
        .clearfix
        .pull-left
          = f.date_select :date_of_formation, { start_year: 50.years.ago.year, end_year: Time.zone.now.year, order: [:month, :day, :year] }, class: "form-control select_auto entity_tenancy_in_common_date_of_formation", style: "#{'display: none;' if f.object.m_date_of_formation?}"
          = f.text_field :date_of_formation, placeholder: 'YYYY-MM-DD', class: 'form-control', style: "#{'display: none;' unless f.object.m_date_of_formation?}"
        .pull-right
          .pull-left
            label Input Date Manually &nbsp; &nbsp; &nbsp; &nbsp;
          .pull-right
            = f.check_box :m_date_of_formation, data: { class: 'entity_tenancy_in_common_date_of_formation' }, class: 'manually_date'

    .clearfix
    - unless @entity.key.present?
      - if available_properties.length == 0
        p.text-info.con-current = "You have 0 properties that can be the property of this Tenancy in Common. Please create a new <span class='ipp-modal' data-id='add-property'><b>Purchased Property</b></span> without an owner.".html_safe
      - elsif available_properties.length == 1
        p.text-info.con-current = "You have 1 property that can be the property of this Tenancy in Common. Therefore, it has been pre-selected. However you could also create a new <span class='ipp-modal' data-id='add-property'><b>Purchased Property</b></span> without an owner if you so desire.".html_safe
      - else
        p.text-info.con-current = "You have #{available_properties.length} properties that can be the property of this Tenancy in Common. However you could also create a new <span class='ipp-modal' data-id='add-property'><b>Purchased Property</b></span> without an owner if you so desire.".html_safe

    - if available_properties.length > 0
      .clearfix
      .form-group.required.margin-sm-top
        label.control-label Property Title
        - if available_properties.length > 1
          = f.select :property_id, options_for_select(available_properties.pluck(:title, :id), f.object.property_id), {}, class: 'form-control'
        - else
          = f.select :property_id, options_for_select(available_properties.pluck(:title, :id), available_properties.pluck(:title, :id).first[1]), {}, class: 'form-control disabled-like', readonly: true

      .form-group
        - if @entity.persisted?
          - c_str = "Warning, you just made changes to #{@entity.name} Are you sure you want to proceed to do this? "
          = f.submit 'Save', class: 'btn btn-sm btn-primary', data: { confirm: c_str }
        - else
          = f.submit 'Save', class: 'btn btn-sm btn-primary'

#popup-should-not-change.corporate
  = hidden_field_tag "should_not_change[name]", (@entity.persisted? ? @entity.reload["name"] : '')
  = hidden_field_tag "should_not_change[ein_or_ssn]", (@entity.persisted? ? @entity.ein_or_ssn : '')
  = hidden_field_tag "should_not_change[date_of_formation]", (@entity.persisted? ? @entity.date_of_formation : '')
  = hidden_field_tag "should_not_change[submit]", false

  .modal.fade#should-not-change-name tabindex="-1" role="dialog" aria-labelledby="should-not-change-name"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading Name should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-name-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-name-cancel data-dismiss="modal" type="button"  Cancel

  .modal.fade#should-not-change-ein tabindex="-2" role="dialog" aria-labelledby="should-not-change-ein"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading EIN number should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-ein-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-ein-cancel data-dismiss="modal" type="button"  Cancel

  .modal.fade#should-not-change-date-of-formation tabindex="-3" role="dialog" aria-labelledby="should-not-change-date-of-formation"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading Date Of Formation should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-date-of-formation-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-date-of-formation-cancel data-dismiss="modal" type="button"  Cancel


/#required_field
/  | All (*) fields are mandatory

/#required_field
/  | All (*) fields are mandatory
/! Modal
#ResourceFormNewProperty.modal.fade aria-hidden="true" aria-labelledby="ResourceFormNewProperty" role="dialog" tabindex="-5"
  .modal-dialog
    .modal-content
      .model-body
        | &nbsp;
      .modal-footer
        button type="button" class="btn btn-primary btn-xs" data-dismiss="modal"
          | close

#ResourceFormProperties.modal.fade aria-hidden="true" aria-labelledby="ResourceFormProperties" role="dialog" tabindex="-5"
  .modal-dialog
    .modal-content
      .model-body
        | &nbsp;
      .modal-footer
        button type="button" class="btn btn-primary btn-xs" data-dismiss="modal"
          | close

app/views/entities/tenancy_in_common/_links.html.slim
- if @entity.key.present?
  .links
    = link_to "Basic info", entities_tenancy_in_common_basic_info_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'basic_info' ? 'active' : ''}"
    = link_to "Tenants in Common", entities_tenancy_in_common_tenants_in_common_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'tenants_in_common' ? 'active' : ''}"
    = link_to "+", entities_tenancy_in_common_tenant_in_common_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'tenant_in_common' ? 'active' : ''}"
    = link_to raw("<span class='glyphicon glyphicon-cog'></span>"), "#", class: "btn btn-sm btn-default margin-sm-left pull-left"

app/views/entities/tenancy_in_common/basic_info.html.slim
- if request.xhr?
  == render partial: "entities/tenancy_in_common/basic_info"
- else
  h2.tic_icp_list.text-center
  .corporate-forms
    == render partial: "entities/tenancy_in_common/links"
    .clearfix
    .corporate-contact-form
      == render partial: "entities/tenancy_in_common/basic_info"

app/views/entities/tenancy_in_common/owns.html.slim
= hidden_field_tag :int_action, 'Ownerships'
.heading
  = "List of #{@entity.display_name}'s Ownerships"
.clearfix
table#data_table
  thead
    tr
      th
        | Name
      th
        | Type
  tbody
    - owns(@entity).each do |item|
      tr
        td
          = link_to item[0], item[1]
        td
          = item[2]

app/views/entities/tenancy_in_common/tenants_in_common.html.slim
= hidden_field_tag :int_action, 'Tenants in Common List'
.clearfix
table#data_table
  thead
    tr
      th
        | Actions
      th
        | Name
      th
        | Type
      th
        | EIN / Social
      th
        | Email
      th
        | Undivided Interest
  tbody
    - @tenants_in_common.each do |object|
      tr
        td.actions
          = link_to 'Edit', entities_tenancy_in_common_tenant_in_common_path( @entity.key, object.id ), remote: true, class: "#{edit_xs} entity-page-xhr"
          = link_to 'Delete', entities_tenancy_in_common_tenant_in_common_path( object.id ), data: {:confirm => 'Are you sure?'}, :method => :delete, remote: true, class: "#{delete_xs} entity-page-xhr"
        td
          - if object.entity.present?
            = link_to object.try(:name), edit_entity_path(object.entity.key)
          - elsif object.contact.present?
            = link_to object.try(:name), edit_contact_path(object.contact)
        td
          = MemberType.member_types[object.member_type_id]
        td
          = object.ein_or_ssn
        td
          = object.email
        td
          = object.my_percentage