config/routes.rb
Rails.application.routes.draw do

  resources :groups
  resources :common_static_fields

  post "/entities/share_or_interest" => "entities#share_or_interest"
  get "/entities/xhr_list" => "entities#xhr_list"
  resources :entities

  namespace :entities do
    get "individuals/basic_info/(:entity_key)" => "individuals#basic_info", as: :individuals_basic_info
    post "individuals/basic_info/(:entity_key)" => "individuals#basic_info"
    patch "individuals/basic_info/:entity_key" => "individuals#basic_info"
    get "individuals/owns/(:entity_key)" => "individuals#owns", as: :individuals_owns
    get "corporates/basic_info/(:entity_key)" => "corporates#basic_info", as: :corporates_basic_info
    post "corporates/basic_info/(:entity_key)" => "corporates#basic_info"
    patch "corporates/basic_info/:entity_key" => "corporates#basic_info"
    get "corporates/contact_info/:entity_key" => "corporates#contact_info", as: :corporates_contact_info
    post "corporates/contact_info/:entity_key" => "corporates#contact_info"
    patch "corporates/contact_info/:entity_key" => "corporates#contact_info"
    get "corporates/directors/:entity_key/(:id)" => "corporates#directors", as: :corporates_directors
    get "corporates/director/:entity_key/(:id)" => "corporates#director", as: :corporates_director
    post "corporates/director/:entity_key/(:id)" => "corporates#director"
    patch "corporates/director/:entity_key/(:id)" => "corporates#director"
    delete "corporates/director/:id" => "corporates#director"
    get "corporates/officers/:entity_key/(:id)" => "corporates#officers", as: :corporates_officers
    get "corporates/officer/:entity_key/(:id)" => "corporates#officer", as: :corporates_officer
    post "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    patch "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    delete "corporates/officer/:id" => "corporates#officer"
    get "corporates/stockholders/:entity_key/(:id)" => "corporates#stockholders", as: :corporates_stockholders
    get "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder", as: :corporates_stockholder
    post "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    patch "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    delete "corporates/stockholder/:id" => "corporates#stockholder"
    get "corporates/owns/(:entity_key)" => "corporates#owns", as: :corporates_owns
    get "llc/basic_info/(:entity_key)" => "llc#basic_info", as: :llc_basic_info
    post "llc/basic_info/(:entity_key)" => "llc#basic_info"
    patch "llc/basic_info/:entity_key" => "llc#basic_info"
    get "llc/contact_info/:entity_key" => "llc#contact_info", as: :llc_contact_info
    post "llc/contact_info/:entity_key" => "llc#contact_info"
    patch "llc/contact_info/:entity_key" => "llc#contact_info"
    get "llc/managers/:entity_key/(:id)" => "llc#managers", as: :llc_managers
    get "llc/manager/:entity_key/(:id)" => "llc#manager", as: :llc_manager
    post "llc/manager/:entity_key/(:id)" => "llc#manager"
    patch "llc/manager/:entity_key/(:id)" => "llc#manager"
    delete "llc/manager/:id" => "llc#manager"
    get "llc/members/:entity_key/(:id)" => "llc#members", as: :llc_members
    get "llc/member/:entity_key/(:id)" => "llc#member", as: :llc_member
    post "llc/member/:entity_key/(:id)" => "llc#member"
    patch "llc/member/:entity_key/(:id)" => "llc#member"
    delete "llc/member/:id" => "llc#member"
    get "llc/owns/(:entity_key)" => "llc#owns", as: :llc_owns
    get "llp/basic_info/(:entity_key)" => "llp#basic_info", as: :llp_basic_info
    post "llp/basic_info/(:entity_key)" => "llp#basic_info"
    patch "llp/basic_info/:entity_key" => "llp#basic_info"
    get "llp/contact_info/:entity_key" => "llp#contact_info", as: :llp_contact_info
    post "llp/contact_info/:entity_key" => "llp#contact_info"
    patch "llp/contact_info/:entity_key" => "llp#contact_info"
    get "llp/partners/:entity_key/(:id)" => "llp#partners", as: :llp_partners
    get "llp/partner/:entity_key/(:id)" => "llp#partner", as: :llp_partner
    post "llp/partner/:entity_key/(:id)" => "llp#partner"
    patch "llp/partner/:entity_key/(:id)" => "llp#partner"
    delete "llp/partner/:id" => "llp#partner"
    get "llp/owns/(:entity_key)" => "llp#owns", as: :llp_owns
    get "partnership/basic_info/(:entity_key)" => "partnership#basic_info", as: :partnership_basic_info
    post "partnership/basic_info/(:entity_key)" => "partnership#basic_info"
    patch "partnership/basic_info/:entity_key" => "partnership#basic_info"
    get "partnership/contact_info/:entity_key" => "partnership#contact_info", as: :partnership_contact_info
    post "partnership/contact_info/:entity_key" => "partnership#contact_info"
    patch "partnership/contact_info/:entity_key" => "partnership#contact_info"
    get "partnership/partners/:entity_key/(:id)" => "partnership#partners", as: :partnership_partners
    get "partnership/partner/:entity_key/(:id)" => "partnership#partner", as: :partnership_partner
    post "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    patch "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    delete "partnership/partner/:id" => "partnership#partner"
    get "partnership/owns/(:entity_key)" => "partnership#owns", as: :partnership_owns
    get "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info", as: :limited_partnership_basic_info
    post "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info"
    patch "limited_partnership/basic_info/:entity_key" => "limited_partnership#basic_info"
    get "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info", as: :limited_partnership_contact_info
    post "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    patch "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    get "limited_partnership/limited_partners/:entity_key/(:id)" => "limited_partnership#limited_partners", as: :limited_partnership_limited_partners
    get "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner", as: :limited_partnership_limited_partner
    post "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    patch "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    delete "limited_partnership/limited_partner/:id" => "limited_partnership#limited_partner"
    get "limited_partnership/general_partners/:entity_key/(:id)" => "limited_partnership#general_partners", as: :limited_partnership_general_partners
    get "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner", as: :limited_partnership_general_partner
    post "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    patch "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    delete "limited_partnership/general_partner/:id" => "limited_partnership#general_partner"
    get "limited_partnership/owns/(:entity_key)" => "limited_partnership#owns", as: :limited_partnership_owns
    get "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info", as: :sole_proprietorship_basic_info
    post "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info"
    patch "sole_proprietorship/basic_info/:entity_key" => "sole_proprietorship#basic_info"
    get "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info", as: :sole_proprietorship_contact_info
    post "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    patch "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    get "sole_proprietorship/owns/(:entity_key)" => "sole_proprietorship#owns", as: :sole_proprietorship_owns
    get "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info", as: :guardianship_basic_info
    post "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info"
    patch "guardianship/basic_info/:entity_key" => "guardianship#basic_info"
    get "guardianship/judge/:entity_key/(:id)" => "guardianship#judge", as: :guardianship_judge
    post "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    patch "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    delete "guardianship/judge/:id" => "guardianship#judge"
    get "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian", as: :guardianship_guardian
    post "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    patch "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    delete "guardianship/guardian/:id" => "guardianship#guardian"
    get "guardianship/ward/:entity_key/(:id)" => "guardianship#ward", as: :guardianship_ward
    post "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    patch "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    delete "guardianship/ward/:id" => "guardianship#ward"
    get "guardianship/owns/(:entity_key)" => "guardianship#owns", as: :guardianship_owns
    get "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info", as: :tenancy_in_common_basic_info
    post "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info"
    patch "tenancy_in_common/basic_info/:entity_key" => "tenancy_in_common#basic_info"
    get "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common", as: :tenancy_in_common_tenant_in_common
    post "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"
    patch "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"

app/models/Entity/agent.rb
class Agent < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Agent")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/beneficiary.rb
class Beneficiary < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "Beneficiary")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  validate :validate_my_percentage
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:beneficiary_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:beneficiary_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:beneficiary_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end

  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/director.rb
class Director < PeopleAndFirm

  belongs_to :entity

  include MyFunction

  default_scope{ where(class_name: "Director")}
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  validate :entity_presence

  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/general_partner.rb
class GeneralPartner < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "GeneralPartner")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  validate :validate_my_percentage
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:partnership_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:partnership_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f == self.total_remaining_share_or_interest
      errors.add(:partnership_interest, " can not be 100%")
      return false
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:partnership_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/guardian.rb
class Guardian < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Guardian")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/judge.rb
class Judge < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Judge")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/concerns/entity_type.rb
class EntityType < MemberType

end

app/views/entities/corporates/_director.html.slim
= form_for @director, url: entities_corporates_director_path(@entity.key, @director.id), html: {class: "entity-page-xhr"} do |f|
  = hidden_field_tag :int_action, 'Add Director'
  - if @director.errors.any?
    #error_explanation
      h2 = "#{pluralize(@director.errors.count, "error")} prohibited this Director from being saved:"
      ul
        - @director.errors.full_messages.each do |message|
          li = message
  .col-lg-4.close-md-4.col-sm-12.col-xs-12
    - prepopulated_directors = options_html('director', "true", @director.super_entity, f.object.temp_id, 'array')

    - if prepopulated_directors.length == 0
      p.text-info = ("You have #{prepopulated_directors.length} individual #{prepopulated_directors.length != 1 ? 'clients or contacts' : 'client or contact'} who could serve as Director of this Corporation. Please create a new individual <span class='ipp-modal' data-id='add-client'><b>Client</b></span> or a new Corporate Director <span class='ipp-modal' data-id='add-contact'><b>Contact</b></span>.").html_safe
    - elsif prepopulated_directors.length == 1
      p.text-info = ("You have #{prepopulated_directors.length} individual #{prepopulated_directors.length != 1 ? 'clients or contacts' : 'client or contact'} who could serve as Director of this Corporation. Since there is only one client or contact, it has been pre-selected. However, you could also create a new <span class='ipp-modal' data-id='add-client'><b>Client</b></span> or a new Coporate Director <span class='ipp-modal' data-id='add-contact'><b>Contact</b></span> if you so desire.").html_safe
    - else
      p.text-info = "You have #{prepopulated_directors.length} individual #{prepopulated_directors.length != 1 ? 'clients or contacts' : 'client or contact'} who could serve as Director of this Corporation. However, you could also create a new <span class='ipp-modal' data-id='add-client'><b>Client</b></span> or a new Coporate Director <span class='ipp-modal' data-id='add-contact'><b>Contact</b></span> if you so desire.".html_safe

    - if prepopulated_directors.length > 0
      .form-group#director_entity
        = hidden_field_tag "director[is_person]", true
        = f.select :temp_id, options_html('director', "true", @director.super_entity, f.object.temp_id), {}, class: "form-control #{'disabled-like' if prepopulated_directors.length == 1}", data: {id: @director.super_entity.id, clienttype: 'director'}, readonly: (prepopulated_directors.length == 1)
        = hidden_field_tag "director[member_type_id]", MemberType.getCorporationId
        = hidden_field_tag :cid, @director.temp_id
      .form-group
        = f.submit 'Save', class: "btn btn-primary"

app/views/entities/corporates/_directors.html.slim
= hidden_field_tag :int_action, 'Directors List'
.clearfix
table#data_table
  thead
    tr
      th
        | Actions
      th
        | First Name
      th
        | Last Name
      th
        | Email
      th
        | phone1
  tbody data-active-id=@activeId
    - @directors.each do |director|
      tr data-id=director.id
        td
          = link_to 'Edit', entities_corporates_director_path(@entity.key, director.id), class: "#{edit_xs} entity-page-xhr"
          = link_to 'Delete', entities_corporates_director_path(director.id), method: :delete, class: "#{delete_xs} entity-page-xhr"
        td
          = director.first_name
        td
          = director.last_name
        td
          = director.email
        td
          = director.phone1

app/views/entities/corporates/_links.html.slim
- if @entity.key.present?
  = link_to "Basic info", entities_corporates_basic_info_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'basic_info' ? 'active' : ''}"
  = link_to "Contact info", entities_corporates_contact_info_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'contact_info' ? 'active' : ''}"
  = link_to "Stockholders", entities_corporates_stockholders_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'stockholders' ? 'active' : ''}"

  = link_to "+", entities_corporates_stockholder_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left stockholder-add entity-page-xhr #{params[:action] == 'stockholder' ? 'active' : ''}"

  = link_to "Officers", entities_corporates_officers_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'officers' ? 'active' : ''}"

  = link_to "+", entities_corporates_officer_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left  pull-leftofficer-add entity-page-xhr #{params[:action] == 'officer' ? 'active' : ''}"

  = link_to "Directors", entities_corporates_directors_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'directors' ? 'active' : ''}"

  = link_to "+", entities_corporates_director_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left director-add entity-page-xhr #{params[:action] == 'director' ? 'active' : ''}"

  = link_to raw("<span class='glyphicon glyphicon-cog'></span>"), "#", class: "btn btn-sm btn-default margin-sm-left pull-left"

  = link_to "Owns", entities_corporates_owns_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'owns' ? 'active' : ''}"

app/views/entities/corporates/_stockholders.html.slim
= hidden_field_tag :int_action, 'Stockholders List'
.clearfix
table#data_table
  thead
    tr
      th
        | Actions
      th
        | Entity Name
      th
        | Type
      th
        | Contact First Name
      th
        | Contact Last Name
      th
        | EIN / Social
      th
        | Client?
      th
        | Phone
      th
        | Email
      th
        | Stock Shares
  tbody data-active-id=@activeId
    - decimal_shares = @entity.shares_decimal_count.nil? ? 0 : @entity.shares_decimal_count
    - @stockholders.each do |stockholder|
      - entity_flag = stockholder.entity.present?
      - person_flag = true
      tr data-id=stockholder.id
        td.actions
          = link_to 'Edit', entities_corporates_stockholder_path(@entity.key, stockholder.id), class: "#{edit_xs} entity-page-xhr"
          = link_to 'Delete', entities_corporates_stockholder_path(stockholder.id), data: {:confirm => 'Are you sure?'}, :method => :delete, class: "#{delete_xs} entity-page-xhr"
        td
          - if !stockholder.is_person?
            - person_flag = false
            - if entity_flag
              = link_to stockholder.entity.try(:name), edit_entity_path(stockholder.entity.key)
            - else
              = link_to stockholder.contact.try(:name), edit_contact_path(stockholder.contact)
        td
          - if entity_flag
            = MemberType.member_types[stockholder.member_type_id]
          - else
            = stockholder.contact.role
        td
          - if person_flag
            - if stockholder.entity.present?
              = link_to stockholder.first_name, edit_entity_path(stockholder.entity.key)
            - elsif stockholder.contact.present?
              = link_to stockholder.first_name, edit_contact_path(stockholder.contact)
          - else
            = stockholder.first_name
        td
          = stockholder.last_name
        td
          = stockholder.ein_or_ssn
        td
          - if stockholder.contact_id.nil?
              = 'Yes'
          - else
              = 'No'
        td
          = stockholder.phone1
        td
          = stockholder.email
        td
          - if decimal_shares >= decimal_places(stockholder.my_percentage_stockholder)
            = number_with_precision(stockholder.my_percentage_stockholder, :precision => decimal_places(stockholder.my_percentage_stockholder))
          - else
            = number_with_precision(stockholder.my_percentage_stockholder, :precision => decimal_shares)

app/views/entities/corporates/basic_info.html.slim
- if request.xhr?
  == render partial: "entities/corporates/basic_info"
- else
  .corporate-forms
    == render partial: "entities/corporates/links"
    .clearfix
    .corporate-contact-form
      == render partial: "entities/corporates/basic_info"

app/views/entities/corporates/contact_info.html.slim
= form_for @entity, url: entities_corporates_contact_info_path(@entity.key), remote: true, html: {class: "entity-page-xhr"} do |f|
  = hidden_field_tag :int_action, 'Contact Info'
  - if @entity.errors.any?
    #error_explanation
      h2 = "#{pluralize(@entity.errors.count, "error")} prohibited this Contact Info from being saved:"
      ul
        - @entity.errors.full_messages.each do |message|
          li = message
  .col-lg-4.close-md-4.col-sm-12.col-xs-12
    .form-group style="display: inline "
      label Honorific
      = f.hidden_field :is_honorific, value: true
      = f.select :honorific, options_for_select(GeneralMethods.honorific, @entity.honorific), {}, {class: "state form-control"}
    .clearfix
    .form-group
      = f.label :first_name, class: "control-label"
      = f.text_field :first_name, class: "form-control"
    .form-group
      = f.label :last_name, class: "control-label"
      = f.text_field :last_name, class: "form-control"
    .form-group
      = f.label :phone1
      = f.text_field :phone1, "placeholder" => "example: +(country code) (phone number)", class: "form-control"
    .form-group
      = f.label :phone2
      = f.text_field :phone2, "placeholder" => "example: +(country code) (phone number)", class: "form-control"
    .form-group
      = f.label :fax
      = f.text_field :fax, class: "form-control"
    .form-group
      = f.label :email
      = f.text_field :email, class: "form-control"
    .form-group
      label Postal Address
      = f.text_field :postal_address, class: "form-control"
    .form-group
      label City
      = f.text_field :city, class: 'city form-control'
    .form-group  
      label State
      = f.select :state, options_for_select(GeneralMethods.USSTATES, @entity.state), html_options: {class: 'state form-control selectize-single'}
    .form-group  
      label Zip
      = f.text_field :zip, class: 'zip form-control'
    .clearfix
      .form-group
        = f.submit 'Save', class: 'btn btn-sm btn-primary'