config/routes.rb
    get "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian", as: :guardianship_guardian
    post "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    patch "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    delete "guardianship/guardian/:id" => "guardianship#guardian"
    get "guardianship/ward/:entity_key/(:id)" => "guardianship#ward", as: :guardianship_ward
    post "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    patch "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    delete "guardianship/ward/:id" => "guardianship#ward"
    get "guardianship/owns/(:entity_key)" => "guardianship#owns", as: :guardianship_owns
    get "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info", as: :tenancy_in_common_basic_info
    post "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info"
    patch "tenancy_in_common/basic_info/:entity_key" => "tenancy_in_common#basic_info"
    get "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common", as: :tenancy_in_common_tenant_in_common
    post "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"
    patch "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"
    delete "tenancy_in_common/tenant_in_common/:id" => "tenancy_in_common#tenant_in_common"
    get "tenancy_in_common/tenants_in_common/:entity_key" => "tenancy_in_common#tenants_in_common", as: :tenancy_in_common_tenants_in_common
    get "tenancy_by_entirety/basic_info/(:entity_key)" => "tenancy_by_entirety#basic_info", as: :tenancy_by_entirety_basic_info
    post "tenancy_by_entirety/basic_info/(:entity_key)" => "tenancy_by_entirety#basic_info"
    patch "tenancy_by_entirety/basic_info/:entity_key" => "tenancy_by_entirety#basic_info"
    get "tenancy_by_entirety/spouse/:entity_key/(:id)" => "tenancy_by_entirety#spouse", as: :tenancy_by_entirety_spouse
    post "tenancy_by_entirety/spouse/:entity_key/(:id)" => "tenancy_by_entirety#spouse"
    patch "tenancy_by_entirety/spouse/:entity_key/(:id)" => "tenancy_by_entirety#spouse"
    delete "tenancy_by_entirety/spouse/:id" => "tenancy_by_entirety#spouse"
    get "tenancy_by_entirety/spouses/:entity_key" => "tenancy_by_entirety#spouses", as: :tenancy_by_entirety_spouses
    get "joint_tenancy/basic_info/(:entity_key)" => "joint_tenancy#basic_info", as: :joint_tenancy_basic_info
    post "joint_tenancy/basic_info/(:entity_key)" => "joint_tenancy#basic_info"
    patch "joint_tenancy/basic_info/:entity_key" => "joint_tenancy#basic_info"
    get "joint_tenancy/joint_tenant/:entity_key/(:id)" => "joint_tenancy#joint_tenant", as: :joint_tenancy_joint_tenant
    post "joint_tenancy/joint_tenant/:entity_key/(:id)" => "joint_tenancy#joint_tenant"
    patch "joint_tenancy/joint_tenant/:entity_key/(:id)" => "joint_tenancy#joint_tenant"
    delete "joint_tenancy/joint_tenant/:id" => "joint_tenancy#joint_tenant"
    get "joint_tenancy/joint_tenants/:entity_key" => "joint_tenancy#joint_tenants", as: :joint_tenancy_joint_tenants
    get "trust/basic_info/(:entity_key)" => "trust#basic_info", as: :trust_basic_info
    post "trust/basic_info/(:entity_key)" => "trust#basic_info"
    patch "trust/basic_info/:entity_key" => "trust#basic_info"
    get "trust/contact_info/:entity_key" => "trust#contact_info", as: :trust_contact_info
    post "trust/contact_info/:entity_key" => "trust#contact_info"
    patch "trust/contact_info/:entity_key" => "trust#contact_info"
    get "trust/settlors/:entity_key/(:id)" => "trust#settlors", as: :trust_settlors
    get "trust/settlor/:entity_key/(:id)" => "trust#settlor", as: :trust_settlor
    post "trust/settlor/:entity_key/(:id)" => "trust#settlor"
    patch "trust/settlor/:entity_key/(:id)" => "trust#settlor"
    delete "trust/settlor/:id" => "trust#settlor"
    get "trust/trustees/:entity_key/(:id)" => "trust#trustees", as: :trust_trustees
    get "trust/trustee/:entity_key/(:id)" => "trust#trustee", as: :trust_trustee
    post "trust/trustee/:entity_key/(:id)" => "trust#trustee"
    patch "trust/trustee/:entity_key/(:id)" => "trust#trustee"
    delete "trust/trustee/:id" => "trust#trustee"
    get "trust/beneficiaries/:entity_key/(:id)" => "trust#beneficiaries", as: :trust_beneficiaries
    get "trust/beneficiary/:entity_key/(:id)" => "trust#beneficiary", as: :trust_beneficiary
    post "trust/beneficiary/:entity_key/(:id)" => "trust#beneficiary"
    patch "trust/beneficiary/:entity_key/(:id)" => "trust#beneficiary"
    delete "trust/beneficiary/:id" => "trust#beneficiary"
    get "trust/owns/(:entity_key)" => "trust#owns", as: :trust_owns
    get "power_of_attorney/basic_info/(:entity_key)" => "power_of_attorney#basic_info", as: :power_of_attorney_basic_info
    post "power_of_attorney/basic_info/(:entity_key)" => "power_of_attorney#basic_info"
    patch "power_of_attorney/basic_info/:entity_key" => "power_of_attorney#basic_info"
    get "power_of_attorney/agents/:entity_key/(:id)" => "power_of_attorney#agents", as: :power_of_attorney_agents
    get "power_of_attorney/agent/:entity_key/(:id)" => "power_of_attorney#agent", as: :power_of_attorney_agent
    post "power_of_attorney/agent/:entity_key/(:id)" => "power_of_attorney#agent"
    patch "power_of_attorney/agent/:entity_key/(:id)" => "power_of_attorney#agent"
    delete "power_of_attorney/agent/:id" => "power_of_attorney#agent"
    get "power_of_attorney/owns/(:entity_key)" => "power_of_attorney#owns", as: :power_of_attorney_owns

  end

  resources :members

  get '/clients/address' => 'clients#address'
  post '/clients/address' => 'clients#address'
  get '/clients/index' => 'clients#index'
  post '/clients/index' => 'clients#index'

  resources :clients do
    collection do
      post :multi_delete
    end
  end

  post '/procedure/actions/checklist_update' => 'procedure/actions#checklist_update'

  get '/procedure/actions/checklist_with_checkbox' => 'procedure/actions#checklist_with_checkbox'
  post '/procedure/actions/checklist_with_checkbox' => 'procedure/actions#checklist_with_checkbox'
  patch '/procedure/actions/checklist_with_checkbox' => 'procedure/actions#checklist_with_checkbox'
  delete '/procedure/actions/checklist_with_checkbox' => 'procedure/actions#checklist_with_checkbox'

  get '/procedure/actions/checklist' => 'procedure/actions#checklist'
  post '/procedure/actions/checklist' => 'procedure/actions#checklist'
  patch '/procedure/actions/checklist' => 'procedure/actions#checklist'
  delete '/procedure/actions/checklist' => 'procedure/actions#checklist'

  get '/procedure/actions/attachment' => 'procedure/actions#attachment'
  post '/procedure/actions/attachment' => 'procedure/actions#attachment'
  patch '/procedure/actions/attachment' => 'procedure/actions#attachment'
  delete '/procedure/actions/attachment' => 'procedure/actions#attachment'

  get '/procedure/actions/member' => 'procedure/actions#member'
  post '/procedure/actions/member' => 'procedure/actions#member'
  patch '/procedure/actions/member' => 'procedure/actions#member'
  delete '/procedure/actions/member' => 'procedure/actions#member'

  get '/properties/member' => 'properties#member'
  post '/properties/member' => 'properties#member'
  patch '/properties/member' => 'properties#member'
  delete '/properties/member' => 'properties#member'

  namespace :procedure do
    resources :actions
  end

  resources :actions
  resources :contacts do
    collection do
      post :multi_delete
    end
  end

  resources :procedures

  get 'comments/property'
  post 'comments/property'

  namespace :property do
    get 'setting' => 'setting#index'
    post 'setting' => 'setting#index'
    get 'setting/emails' => 'setting#emails'
    delete 'setting/emails' => 'setting#emails'
  end

  resources :properties do
    collection do
      post :multi_delete
    end
  end

  resources :transaction_property_offers do
    member do
      patch :update_with_contact
    end
  end
  resources :counteroffers

  resources :transaction_baskets do
    collection do
      post :identify_basket_to_qi
    end
  end

  resources :transactions do
    member do
      get :edit_qualified_intermediary, :properties_edit, :qualified_intermediary,
        :terms, :inspection, :closing, :personnel, :get_status, :qi_status
      patch :qualified_intermediary, :properties_update, :terms_update, :inspection_update, :personnel_update, :set_status
      post :personnel_update
      post :closing
    end
    collection do
      post :multi_delete
      get :delete_transaction_property
    end
  end

  resources :transaction_sales, path: :transactions
  resources :transaction_purchases, path: :transactions

  resources :dynamic_fields

  namespace :admin do
    resources :admins do
      member do
        post :set_unset
      end
    end

    resources :users do
      member do
        post :set_unset, :enable_disable
      end
    end

    resources :clients do

    end

    resources :transactions do

    end

    resources :contacts do
      collection do
        get :personnel
      end
    end

    resources :properties do
      collection do
        get :sold_to_purchased
      end
    end

    resources :tenants do
      
    end
    
    resources :default_values do
      collection do
        get :new_property, :new_terms, :new_purchase_property, :new_sell_property,
            :new_sale_transaction
        post :random_mode
        post :toggle_landing_page
        post :toggle_initial_sign_in_modal
        post :set_greeting
        post :toggle_personnel_to_user
      end
    end

  end

  post '/users/set_contact_info' => 'users#set_contact_info'
  get '/users/profile' => 'users#profile'
  
  devise_for :users, :controllers => { }

  root 'home#index'

  get '/initial-participants' => 'home#initial_participants'

  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::AdminController
  
  def resource_class_with_condition
    if params[:klazz].blank?
      TransactionSale
    else
      params[:klazz].constantize
    end
  end
  
  def index
    @resources = resource_class_with_condition.with_deleted.joins(:transaction_main)
    @resources = @resources.where('transaction_mains.init' => false)
    @resources = @resources.where('transactions.deleted_at' => nil) unless params[:trashed].to_b
    @resources = @resources.where.not('transactions.deleted_at' => nil) if params[:trashed].to_b
    @resources = @resources.order('transactions.created_at DESC').paginate(page: params[:page], per_page: 10)
    
    respond_to do |format|
      format.html
    end
  
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
    def get_transaction_properties(transaction)
        if transaction.present?
            transaction_property_ids = transaction.transaction_properties.where(is_selected: true).pluck(:property_id)
            properties = Property.where(id: transaction_property_ids).order(created_at: :desc)
        else
            properties = []
        end

        return properties
    end

    def get_property_step(property_id, trans_main_id, is_sale = true)
        cur_step = TransactionProperty.where(property_id: property_id).where(transaction_main_id: trans_main_id).where(is_sale: is_sale).first

        return cur_step
    end

    def get_property(property_id)
        return Property.find(property_id)
    end

    def get_recent_counteroffer_price(transaction_property_offer)
        last_offered_price = transaction_property_offer.counteroffers.where("offered_price IS NOT NULL AND offered_date IS NOT NULL").order(updated_at: :asc).last.try(:offered_price)
        if last_offered_price
            return number_to_currency(last_offered_price)
        else
            return ""
        end
    end

    def get_property_purchaser_or_seller(property_id, transaction_id, type="sale")
        if type == 'sale'
            is_sale = true
        else
            is_sale = false
        end
        transaction_property = TransactionProperty.where(property_id: property_id).where(transaction_id: transaction_id).where(is_sale: is_sale).first
        if transaction_property.present?
            accepted_offer = transaction_property.transaction_property_offers.where(is_accepted: true).first
            if accepted_offer.present?
                if transaction_property.is_sale
                    return Contact.find(accepted_offer.client_contact_id)
                else
                    return transaction_property.owner
                end
            end
        else
            return false
        end
    end

    def get_sale_price(transaction_property)
        accepted_offer = transaction_property.transaction_property_offers.where(is_accepted: true).first
        if accepted_offer.present?
            if accepted_offer.accepted_counteroffer_id == 0
                return transaction_property.sale_price
            else
                return Counteroffer.find(accepted_offer.accepted_counteroffer_id).try(:offered_price)
            end
        else
            return ''
        end
    end

    def is_property_closed?(transaction_id, property_id)
      retVal = false
      p = TransactionProperty.where(transaction_id: transaction_id, property_id: property_id).first
      retVal = p.closed? if !p.nil?
      return retVal
    end

    def is_property_in_contract?(transaction_id, property_id)
      retVal = false
      p = TransactionProperty.where(transaction_id: transaction_id, property_id: property_id).first
      retVal = p.is_in_contract? if !p.nil?
      return retVal
    end

    def get_purchase_property_costs(transaction, transaction_basket = nil)
        total_purchase_cost_of_contracted = 0
        total_purchase_cost_of_contracted_selected = 0
        if transaction_basket.nil?
            basket_properties = transaction.transaction_properties.where(is_selected: true).pluck(:property_id)
        else
            basket_properties = transaction_basket.transaction_basket_properties.pluck(:property_id)
        end
        transaction.transaction_properties.each do |transaction_property|
            if basket_properties.include? transaction_property.property_id
                if transaction_property.closed?
                    # do something
                elsif transaction_property.is_in_contract?
                    total_purchase_cost_of_contracted += transaction_property.sale_price || 0
                    total_purchase_cost_of_contracted_selected += transaction_property.sale_price || 0
                else
                    if transaction_property.is_selected
                        total_purchase_cost_of_contracted_selected += transaction_property.sale_price || 0
                    else
                        total_purchase_cost_of_contracted_selected += transaction_property.property.price || 0
                    end
                end
            end
        end
    
        return [total_purchase_cost_of_contracted, total_purchase_cost_of_contracted_selected]
    end

    def get_est_identification_bugdets(transaction)
        total_est_budget_of_closed = 0
        total_est_budget_of_closed_contracted = 0
        total_est_budget_of_closed_contracted_selected = 0
        transaction.transaction_properties.where(is_selected: true).each do |transaction_property|
            if transaction_property.closed?
                total_est_budget_of_closed += transaction_property.closing_proceeds || 0
                total_est_budget_of_closed_contracted += transaction_property.closing_proceeds || 0
                total_est_budget_of_closed_contracted_selected += transaction_property.closing_proceeds || 0
            elsif transaction_property.is_in_contract?
                total_est_budget_of_closed_contracted += transaction_property.sale_price * 0.1 || 0
                total_est_budget_of_closed_contracted_selected += transaction_property.sale_price * 0.1 || 0
            else
                total_est_budget_of_closed_contracted_selected += transaction_property.sale_price * 0.1 || 0
            
            end
        end
        
        return [total_est_budget_of_closed * 2, total_est_budget_of_closed_contracted * 2, total_est_budget_of_closed_contracted_selected * 2]
    end

    def is_exist_identified_basket(transaction)
        if transaction.transaction_baskets.where(is_identified_to_qi: true).count > 0
            return true
        else
            return false
        end
    end

    def get_identification_rule(transaction)
        if transaction.present?
            identified_basket = transaction.transaction_baskets.where(is_identified_to_qi: true).first
            if identified_basket.present?
                case identified_basket.identification_rule
                when 'three_property'
                    return "Three Property"
                when '200%'
                    return "200%"
                when '95%'
                    return "95%"
                end
            else
                return ''
            end
        else
            return ''
        end
    end
end

app/views/transactions/_breadcrum.slim
.col-lg-12.col-md-12.col-sm-12.col-xs-12
  .page-title
    .title_left
      .pull-left
        h5
          - if defined?(@transaction) && @transaction.present?
            - if @transaction.Sale? && @transaction.relinquishing_seller_entity
              = link_to 'Transaction (' + @transaction.seller_name + ' )', transactions_path
            - elsif @transaction.Purchase? && @transaction.replacement_purchaser_entity
                = link_to 'Transaction ( ' + @transaction.purchaser_name + ' )', transactions_path
            - else
              = link_to 'Transaction', transactions_path      
          - else
            = link_to 'Transaction', transactions_path
      - if params[:type] == 'qi_status'
        .pull-left
          h5
            | &nbsp;&nbsp;/&nbsp;&nbsp;
        .pull-left
          h5
            = link_to  'QI', qi_status_transaction_path(@transaction, main_id: @transaction_main.id)
      - elsif params[:sub] == 'personnel'
        .pull-left
          h5
            | &nbsp;&nbsp;/&nbsp;&nbsp;
        .pull-left
          h5
            = link_to  'Personnel', personnel_transaction_path(@transaction, sub: 'personnel', main_id: params[:main_id])
      - else        
        - if defined?(@transaction) && @transaction.present? && @transaction.Sale? && params[:type] != 'status'
          .pull-left
            h5
              | &nbsp;&nbsp;/&nbsp;&nbsp;

          .pull-left
            h5 
              = link_to (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type]) : '#') do
                - if params[:cur_property]
                  - selected_property = get_property(params[:cur_property]) 
                  - if selected_property.present? 
                    = 'Sale ( ' + selected_property.try(:title) + ' )'
                  - else
                    | Sale
                - else
                  | Sale

        - if defined?(@transaction) && @transaction.present? && @transaction.Purchase? && params[:type] != 'status'
          .pull-left
            h5
              | &nbsp;&nbsp;/&nbsp;&nbsp;
          .pull-left
            h5
              = link_to (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type]) : '#') do
                - if params[:cur_property]
                  - selected_property = get_property(params[:cur_property]) 
                  - if selected_property.present?
                    = 'Purchase ( ' + selected_property.try(:title) + ' )'
                  - else
                    | Purchase
                - else
                  | Purchase

        - if defined?(@transaction) && @transaction.present? && params[:type] != 'status'
          .pull-left
            h5
              | &nbsp;&nbsp;/&nbsp;&nbsp;
          .pull-left
            - if params[:sub].blank?
              - if @transaction.Sale?
                h5 = link_to " #{(@transaction.relinquishing_seller_entity_id ? '' : 'Identify the Relinquishing Seller')}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
            - else  
              - case params[:sub]
                - when 'parties'
                  - if @transaction.Sale?
                    h5 = link_to " #{(@transaction.relinquishing_seller_entity_id ? '' : 'Identify the Relinquishing Seller')}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
                  - else
                    h5 = link_to " #{(@transaction.replacement_seller_contact_id ? '' : 'Identify the Replacement Seller')}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
                - when 'property'
                  h5 = link_to " #{(@transaction.Sale? ? 'Select Property to Sell' : 'Select Property to Buy' )}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
                - when 'terms'
                  h5 = link_to " #{(@transaction.Sale? ? 'Negotiate the Sales Price with the Prospective Purchaser' : params[:sub])}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
                - when 'inspection'
                  h5 = link_to " #{params[:sub]}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
                - when 'closing'
                  h5 = link_to " #{params[:sub]}", (@transaction.id.present? ? edit_transaction_url(@transaction.id, main_id: params[:main_id], type: params[:type], sub: params[:sub]) : '#')
        - if params[:type] == 'status'
          .pull-left
            h5
              | &nbsp;&nbsp;/&nbsp;&nbsp;
          .pull-left
            h5
              = link_to 'Status', defined?(@transaction_main) && @transaction_main.persisted? ? get_status_transaction_path(@transaction_main, type: 'status', main_id: @transaction_main) : '#', class: ""
      
            
    .title_right.note-list
      .col-xs-12.form-group.pull-right.top_search
        a[href="javascript:;"]
          i.fa.fa-circle.text-danger
          span
            | &nbsp;&nbsp;&nbsp;Notes&nbsp;&nbsp;&nbsp;
          span.fa.fa-pencil-square-o.fa-2x
input#global_transaction_type[type='hidden' value="#{params[:type]}"]

app/views/transactions/_closing.slim
- if @transaction.is_a?(TransactionSale)
  == render partial: 'transactions/sale_wizard/sale_closing'
- elsif @transaction.is_a?(TransactionPurchase)
  == render partial: 'transactions/purchase_wizard/purchase_closing'

app/views/transactions/_form.html.slim
- if @transaction.is_a?(TransactionPurchase)
  = render partial: 'transactions/purchase_wizard/purchase_form'
- elsif @transaction.is_a?(TransactionSale)
  = render partial: 'transactions/sale_wizard/sale_form'

app/views/transactions/_header_link.slim
- $header_links = {}
- css_class = 'btn btn-sm btn-default margin-sm-left'
hr
- if params[:type] != 'qi_status' && params[:sub] != 'personnel'
  - persisted = @transaction.persisted?
  - if @transaction.is_a?(TransactionSale)
    .form_wizard.wizard_horizontal
      ul.wizard_steps
        li class=("#{'selected' if params[:sub] == 'parties' || params[:sub].blank? }")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status'
          - $header_links[:parties] = persisted ? edit_transaction_path(@transaction, sub: 'parties', type: 'sale', main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Who's Selling?</span>".html_safe, $header_links[:parties]

        li class=("#{'selected' if params[:sub] == 'property'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:properties] = persisted ? properties_edit_transaction_path(@transaction, sub: 'property', type: 'sale', main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>What's For Sale?</span>".html_safe, $header_links[:properties]

        li class=("#{'selected' if params[:sub] == 'terms'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:terms] = persisted ? terms_transaction_path(@transaction, sub: 'terms', type: 'sale', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Negotiations</span>".html_safe, $header_links[:terms]

        li class=("#{'selected' if params[:sub] == 'inspection'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:inspection] = persisted ? inspection_transaction_path(@transaction, sub: 'inspection', type: 'sale', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Inspection</span>".html_safe, $header_links[:inspection]

        - pclosed = is_property_closed?(@transaction_main.sale.try(:id) || 0, params[:cur_property])
        li (class="#{ pclosed ? 'closed' : params[:sub] == 'closing' ? 'selected' : '' }")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:closing] = persisted ? closing_transaction_path(@transaction, sub: 'closing', type: 'sale', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Closing</span>".html_safe, $header_links[:closing]
        
        li
          - if params[:type] != 'qi_status' && params[:sub] != 'closing'
            button#save-and-next.btn.btn-default.border-blue.blue[href=""] Save & Next

  - else @transaction.is_a?(TransactionPurchase)

    .form_wizard.wizard_horizontal
      ul.wizard_steps
        li class=("#{'selected' if params[:sub] == 'property' || params[:sub].blank?}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:properties] = persisted ? properties_edit_transaction_path(@transaction, sub: 'property', type: 'purchase', main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>What's being Bought?</span>".html_safe, $header_links[:properties]

        li class=("#{'selected' if params[:sub] == 'terms'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:terms] = persisted ? terms_transaction_path(@transaction, sub: 'terms', type: 'purchase', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Negotiations</span>".html_safe, $header_links[:terms]

        li class=("#{'selected' if params[:sub] == 'parties' }")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status'
          - $header_links[:parties] = persisted ? edit_transaction_path(@transaction, sub: 'parties', type: 'purchase', main_id: params[:main_id], cur_property: params[:cur_property]) : '#'
          = link_to "<span class='step_no'>Who's the Seller?</span>".html_safe, $header_links[:parties]

        li class=("#{'selected' if params[:sub] == 'inspection'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:inspection] = persisted ? inspection_transaction_path(@transaction, sub: 'inspection', type: 'purchase', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Inspection</span>".html_safe, $header_links[:inspection]

        li class=("#{'selected' if params[:sub] == 'closing'}")
          - disabled = nil
          - disabled = 'disabled' if params[:type] == 'status' || @transaction.new_record?
          - $header_links[:closing] = persisted ? closing_transaction_path(@transaction, sub: 'closing', type: 'purchase', cur_property: params[:cur_property], main_id: params[:main_id]) : '#'
          = link_to "<span class='step_no'>Closing</span>".html_safe, $header_links[:closing]

        li
          - if params[:type] != 'qi_status' && params[:sub] != 'closing'
            button#save-and-next.btn.btn-default.border-blue.blue[href=""] Save & Next

app/views/transactions/_parties.slim
= render partial: 'transactions/form'

app/views/transactions/_property.slim
- if @transaction.is_a?(TransactionPurchase)
  = render partial: 'transactions/purchase_wizard/purchase_property'
- elsif @transaction.is_a?(TransactionSale)
  = render partial: 'transactions/sale_wizard/sale_property'