config/routes.rb
Rails.application.routes.draw do

  resources :groups
  resources :common_static_fields

  post "/entities/share_or_interest" => "entities#share_or_interest"
  get "/entities/xhr_list" => "entities#xhr_list"
  resources :entities

  namespace :entities do
    get "individuals/basic_info/(:entity_key)" => "individuals#basic_info", as: :individuals_basic_info
    post "individuals/basic_info/(:entity_key)" => "individuals#basic_info"
    patch "individuals/basic_info/:entity_key" => "individuals#basic_info"
    get "individuals/owns/(:entity_key)" => "individuals#owns", as: :individuals_owns
    get "corporates/basic_info/(:entity_key)" => "corporates#basic_info", as: :corporates_basic_info
    post "corporates/basic_info/(:entity_key)" => "corporates#basic_info"
    patch "corporates/basic_info/:entity_key" => "corporates#basic_info"
    get "corporates/contact_info/:entity_key" => "corporates#contact_info", as: :corporates_contact_info
    post "corporates/contact_info/:entity_key" => "corporates#contact_info"
    patch "corporates/contact_info/:entity_key" => "corporates#contact_info"
    get "corporates/directors/:entity_key/(:id)" => "corporates#directors", as: :corporates_directors
    get "corporates/director/:entity_key/(:id)" => "corporates#director", as: :corporates_director
    post "corporates/director/:entity_key/(:id)" => "corporates#director"
    patch "corporates/director/:entity_key/(:id)" => "corporates#director"
    delete "corporates/director/:id" => "corporates#director"
    get "corporates/officers/:entity_key/(:id)" => "corporates#officers", as: :corporates_officers
    get "corporates/officer/:entity_key/(:id)" => "corporates#officer", as: :corporates_officer
    post "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    patch "corporates/officer/:entity_key/(:id)" => "corporates#officer"
    delete "corporates/officer/:id" => "corporates#officer"
    get "corporates/stockholders/:entity_key/(:id)" => "corporates#stockholders", as: :corporates_stockholders
    get "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder", as: :corporates_stockholder
    post "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    patch "corporates/stockholder/:entity_key/(:id)" => "corporates#stockholder"
    delete "corporates/stockholder/:id" => "corporates#stockholder"
    get "corporates/owns/(:entity_key)" => "corporates#owns", as: :corporates_owns
    get "llc/basic_info/(:entity_key)" => "llc#basic_info", as: :llc_basic_info
    post "llc/basic_info/(:entity_key)" => "llc#basic_info"
    patch "llc/basic_info/:entity_key" => "llc#basic_info"
    get "llc/contact_info/:entity_key" => "llc#contact_info", as: :llc_contact_info
    post "llc/contact_info/:entity_key" => "llc#contact_info"
    patch "llc/contact_info/:entity_key" => "llc#contact_info"
    get "llc/managers/:entity_key/(:id)" => "llc#managers", as: :llc_managers
    get "llc/manager/:entity_key/(:id)" => "llc#manager", as: :llc_manager
    post "llc/manager/:entity_key/(:id)" => "llc#manager"
    patch "llc/manager/:entity_key/(:id)" => "llc#manager"
    delete "llc/manager/:id" => "llc#manager"
    get "llc/members/:entity_key/(:id)" => "llc#members", as: :llc_members
    get "llc/member/:entity_key/(:id)" => "llc#member", as: :llc_member
    post "llc/member/:entity_key/(:id)" => "llc#member"
    patch "llc/member/:entity_key/(:id)" => "llc#member"
    delete "llc/member/:id" => "llc#member"
    get "llc/owns/(:entity_key)" => "llc#owns", as: :llc_owns
    get "llp/basic_info/(:entity_key)" => "llp#basic_info", as: :llp_basic_info
    post "llp/basic_info/(:entity_key)" => "llp#basic_info"
    patch "llp/basic_info/:entity_key" => "llp#basic_info"
    get "llp/contact_info/:entity_key" => "llp#contact_info", as: :llp_contact_info
    post "llp/contact_info/:entity_key" => "llp#contact_info"
    patch "llp/contact_info/:entity_key" => "llp#contact_info"
    get "llp/partners/:entity_key/(:id)" => "llp#partners", as: :llp_partners
    get "llp/partner/:entity_key/(:id)" => "llp#partner", as: :llp_partner
    post "llp/partner/:entity_key/(:id)" => "llp#partner"
    patch "llp/partner/:entity_key/(:id)" => "llp#partner"
    delete "llp/partner/:id" => "llp#partner"
    get "llp/owns/(:entity_key)" => "llp#owns", as: :llp_owns
    get "partnership/basic_info/(:entity_key)" => "partnership#basic_info", as: :partnership_basic_info
    post "partnership/basic_info/(:entity_key)" => "partnership#basic_info"
    patch "partnership/basic_info/:entity_key" => "partnership#basic_info"
    get "partnership/contact_info/:entity_key" => "partnership#contact_info", as: :partnership_contact_info
    post "partnership/contact_info/:entity_key" => "partnership#contact_info"
    patch "partnership/contact_info/:entity_key" => "partnership#contact_info"
    get "partnership/partners/:entity_key/(:id)" => "partnership#partners", as: :partnership_partners
    get "partnership/partner/:entity_key/(:id)" => "partnership#partner", as: :partnership_partner
    post "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    patch "partnership/partner/:entity_key/(:id)" => "partnership#partner"
    delete "partnership/partner/:id" => "partnership#partner"
    get "partnership/owns/(:entity_key)" => "partnership#owns", as: :partnership_owns
    get "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info", as: :limited_partnership_basic_info
    post "limited_partnership/basic_info/(:entity_key)" => "limited_partnership#basic_info"
    patch "limited_partnership/basic_info/:entity_key" => "limited_partnership#basic_info"
    get "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info", as: :limited_partnership_contact_info
    post "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    patch "limited_partnership/contact_info/:entity_key" => "limited_partnership#contact_info"
    get "limited_partnership/limited_partners/:entity_key/(:id)" => "limited_partnership#limited_partners", as: :limited_partnership_limited_partners
    get "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner", as: :limited_partnership_limited_partner
    post "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    patch "limited_partnership/limited_partner/:entity_key/(:id)" => "limited_partnership#limited_partner"
    delete "limited_partnership/limited_partner/:id" => "limited_partnership#limited_partner"
    get "limited_partnership/general_partners/:entity_key/(:id)" => "limited_partnership#general_partners", as: :limited_partnership_general_partners
    get "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner", as: :limited_partnership_general_partner
    post "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    patch "limited_partnership/general_partner/:entity_key/(:id)" => "limited_partnership#general_partner"
    delete "limited_partnership/general_partner/:id" => "limited_partnership#general_partner"
    get "limited_partnership/owns/(:entity_key)" => "limited_partnership#owns", as: :limited_partnership_owns
    get "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info", as: :sole_proprietorship_basic_info
    post "sole_proprietorship/basic_info/(:entity_key)" => "sole_proprietorship#basic_info"
    patch "sole_proprietorship/basic_info/:entity_key" => "sole_proprietorship#basic_info"
    get "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info", as: :sole_proprietorship_contact_info
    post "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    patch "sole_proprietorship/contact_info/:entity_key" => "sole_proprietorship#contact_info"
    get "sole_proprietorship/owns/(:entity_key)" => "sole_proprietorship#owns", as: :sole_proprietorship_owns
    get "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info", as: :guardianship_basic_info
    post "guardianship/basic_info/(:entity_key)" => "guardianship#basic_info"
    patch "guardianship/basic_info/:entity_key" => "guardianship#basic_info"
    get "guardianship/judge/:entity_key/(:id)" => "guardianship#judge", as: :guardianship_judge
    post "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    patch "guardianship/judge/:entity_key/(:id)" => "guardianship#judge"
    delete "guardianship/judge/:id" => "guardianship#judge"
    get "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian", as: :guardianship_guardian
    post "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    patch "guardianship/guardian/:entity_key/(:id)" => "guardianship#guardian"
    delete "guardianship/guardian/:id" => "guardianship#guardian"
    get "guardianship/ward/:entity_key/(:id)" => "guardianship#ward", as: :guardianship_ward
    post "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    patch "guardianship/ward/:entity_key/(:id)" => "guardianship#ward"
    delete "guardianship/ward/:id" => "guardianship#ward"
    get "guardianship/owns/(:entity_key)" => "guardianship#owns", as: :guardianship_owns
    get "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info", as: :tenancy_in_common_basic_info
    post "tenancy_in_common/basic_info/(:entity_key)" => "tenancy_in_common#basic_info"
    patch "tenancy_in_common/basic_info/:entity_key" => "tenancy_in_common#basic_info"
    get "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common", as: :tenancy_in_common_tenant_in_common
    post "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"
    patch "tenancy_in_common/tenant_in_common/:entity_key/(:id)" => "tenancy_in_common#tenant_in_common"

app/models/Entity/agent.rb
class Agent < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Agent")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/beneficiary.rb
class Beneficiary < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "Beneficiary")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  validate :validate_my_percentage
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:beneficiary_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:beneficiary_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:beneficiary_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end

  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/director.rb
class Director < PeopleAndFirm

  belongs_to :entity

  include MyFunction

  default_scope{ where(class_name: "Director")}
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  validate :entity_presence

  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/general_partner.rb
class GeneralPartner < PeopleAndFirm

  include MyFunction
  include ModelMethods

  default_scope{ where(class_name: "GeneralPartner")}
  validate :entity_presence
  # validates_presence_of :first_name, :last_name
  validates_length_of :first_name, :last_name, :email, :phone_number, maximum: 250
  validate :remaining_share_or_interest_check
  belongs_to :super_entity, class_name: "SuperEntity"
  belongs_to :entity
  validate :validate_my_percentage
  belongs_to :contact
  after_save :add_key

  attr_accessor :share_error

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def validate_my_percentage

    if self.remaining_share_or_interest_ <= 0
      errors.add(:share_error, "now remaining is Zero")
      return
    end

    if self.my_percentage.blank?
      errors.add(:partnership_interest, "can not be blank")
      return
    end

    if self.my_percentage.to_f <= 0
      errors.add(:partnership_interest, "must be more than zero")
      return
    end

    if self.my_percentage.to_f == self.total_remaining_share_or_interest
      errors.add(:partnership_interest, " can not be 100%")
      return false
    end

    if self.my_percentage.to_f > self.remaining_share_or_interest_
      errors.add(:partnership_interest, "must be less than or equal to #{self.remaining_share_or_interest_} %")
      return
    end
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/guardian.rb
class Guardian < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Guardian")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/Entity/judge.rb
class Judge < PeopleAndFirm

  include MyFunction

  default_scope{ where(class_name: "Judge")}
  validate :entity_presence
  # validate :phone_validation
  # validates_presence_of :first_name, :last_name
  validates :email, email: true, if: "self.email.present?"
  validates_length_of :first_name, :last_name, :email, :postal_address, :fax, :phone1, :phone2, :city, :state, :zip, maximum: 250
  after_save :add_key
  belongs_to :super_entity, class_name: "SuperEntity"

  belongs_to :entity
  belongs_to :contact

  def entity_presence
    if self.entity.blank? && self.contact.blank? && self.first_name.blank? && self.last_name.blank? && self.temp_id.blank?
      errors.add(:entity, "is invalid, Please add it before saving")
      return
    end
  end

  def type_
    MemberType.find(Entity.find(self.entity_id).type_).name rescue ""
  end

  def name
    if self.entity.present?
      self.entity.name
    elsif self.contact.present?
      self.contact.name
    else
      "#{self.first_name} #{self.last_name}"
    end
  end

end

app/models/concerns/entity_type.rb
class EntityType < MemberType

end

app/views/entities/llc/_basic_info.html.slim
- if @just_created.present?
  .modal.fade#entity-creation-message tabindex="-3" role="dialog" aria-labelledby="entity-creation-message"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .corporation-creation-message
            = "Congratulations you have just created #{@entity.display_name}."
        .modal-footer
          button.btn.btn-primary.should-not-change-date-of-formation-cancel data-dismiss="modal" type="button"  Close

= form_for @entity, url: entities_llc_basic_info_path( @entity.key ), html: { class: "entity-page-xhr" } do |f|
  - if @entity.errors.any?
    #error_explanation
      h2 = "#{pluralize(@entity.errors.count, "error")} prohibited this LLC from being saved:"
      ul
        - override_active_record_errors(@entity.errors.messages, {base: ''}).each do |message|
          li = message
  .col-lg-4.close-md-4.col-sm-12.col-xs-12
    .form-group.required
      = f.label "name", class: "control-label"
      .clearfix
      = f.text_field :name, class: "form-control width-field-md pull-left"
      div
        = f.hidden_field :has_comma, class: "has_comma_val"
        = image_tag('Comma.png', :id=> 'comma', :width => '30px', :height=> '30px', :class => 'pull-left')
        = image_tag('Comma-grey.png', :id=> 'comma-grey', :width => '30px', :height=> '30px', :class => 'pull-left')
        span.name-suffix-span.pull-left
          | LLC
        = f.hidden_field :legal_ending, :value => "LLC"
      .clearfix
      = linkbacks_entity(@entity)
    .form-group
      = f.label "Ein"
      = f.text_field :ein_or_ssn, class: "form-control"

    .clearfix
    .form-group.required
      label.control-label Date of Formation
      .clearfix
      .pull-left
        = f.date_select :date_of_formation, { start_year: 50.years.ago.year, end_year: Time.zone.now.year, order: [:month, :day, :year] }, class: "form-control select_auto entity_date_of_formation", style: "#{'display: none;' if f.object.m_date_of_formation?}"
        = f.text_field :date_of_formation, placeholder: 'YYYY-MM-DD', class: 'form-control', style: "#{'display: none;' unless f.object.m_date_of_formation?}"
      .pull-right
        .pull-left
          label Input Date Manually &nbsp; &nbsp; &nbsp; &nbsp;
        .pull-right
          = f.check_box :m_date_of_formation, data: { class: 'entity_date_of_formation' }, class: 'manually_date'

    .clearfix
    .form-group.margin-sm-top
      = f.label "State of Formation"
      = f.select :jurisdiction, options_for_select(Entity.USSTATES, @entity.jurisdiction), {}, class: "form-control selectize-single width-field-md"
    - if @entity.persisted?
      .form-group
        .part123.heading
          = "#{(100 - Member.new(super_entity_id: @entity.id).remaining_share_or_interest rescue 0) }% of Member's Interest have been assigned out of 100%"
    .clearfix
      .form-group
        - if @entity.persisted?
          - c_str = "Warning, you just made changes to #{@entity.display_name} Are you sure you want to proceed to do this? "
          = f.submit 'Save', class: 'btn btn-sm btn-primary', data: { confirm: c_str }
        - else
          = f.submit 'Save', class: 'btn btn-sm btn-primary'


#popup-should-not-change.corporate
  = hidden_field_tag "should_not_change[name]", (@entity.persisted? ? @entity.reload["name"] : '')
  = hidden_field_tag "should_not_change[ein_or_ssn]", (@entity.persisted? ? @entity.ein_or_ssn : '')
  = hidden_field_tag "should_not_change[date_of_formation]", (@entity.persisted? ? @entity.date_of_formation : '')
  = hidden_field_tag "should_not_change[submit]", false

  .modal.fade#should-not-change-name tabindex="-1" role="dialog" aria-labelledby="should-not-change-name"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading Name should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-name-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-name-cancel data-dismiss="modal" type="button"  Cancel

  .modal.fade#should-not-change-ein tabindex="-2" role="dialog" aria-labelledby="should-not-change-ein"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading EIN number should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-ein-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-ein-cancel data-dismiss="modal" type="button"  Cancel

  .modal.fade#should-not-change-date-of-formation tabindex="-3" role="dialog" aria-labelledby="should-not-change-date-of-formation"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          .heading Date Of Formation should never change -- are you sure you want to change it?
        .modal-footer
          button.btn.btn-default.should-not-change-date-of-formation-yes type="button"  Yes
          button.btn.btn-primary.should-not-change-date-of-formation-cancel data-dismiss="modal" type="button"  Cancel


/#required_field
/  | All (*) fields are mandatory

app/views/entities/llc/_links.html.slim
- if @entity.key.present?
  = link_to "Basic info", entities_llc_basic_info_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'basic_info' ? 'active' : ''}"
  = link_to "Contact info", entities_llc_contact_info_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'contact_info' ? 'active' : ''}"

  = link_to "Members", entities_llc_members_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'members' ? 'active' : ''}"
  = link_to "+", entities_llc_member_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left stockholder-add entity-page-xhr #{params[:action] == 'member' ? 'active' : ''}"
  = link_to "Managers", entities_llc_managers_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'managers' ? 'active' : ''}"
  = link_to "+", entities_llc_manager_path(@entity.key), class: "btn btn-sm btn-default margin-sm-left pull-left director-add entity-page-xhr #{params[:action] == 'manager' ? 'active' : ''}"
  = link_to raw("<span class='glyphicon glyphicon-cog'></span>"), "#", class: "btn btn-sm btn-default margin-sm-left pull-left"
  = link_to "Owns", entities_llc_owns_path(@entity.key), remote: true, class: "btn btn-sm btn-default margin-sm-left pull-left entity-page-xhr #{params[:action] == 'owns' ? 'active' : ''}"

app/views/entities/llc/_managers.html.slim
= hidden_field_tag :int_action, 'Managers List'
.clearfix
table#data_table
  thead
    tr
      th
        | Actions
      th
        | First Name
      th
        | Last Name
      th
        | Email
      th
        | phone1
  tbody data-active-id=@activeId
    - @managers.each do |manager|
      tr data-id=manager.id
        td
          - if manager.is_a?(Manager)
            = link_to 'Edit', entities_llc_manager_path(@entity.key, manager.id), class: "#{edit_xs} entity-page-xhr"
            = link_to 'Delete', entities_llc_manager_path(manager.id), method: :delete, class: "#{delete_xs} entity-page-xhr"
          - elsif manager.is_a?(Member)
            = link_to 'Edit', entities_llc_member_path( @entity.key, manager.id ), class: "#{edit_xs} entity-page-xhr"
            = link_to 'Delete', entities_llc_member_path( manager.id ), data: {:confirm => 'Are you sure?'}, :method => :delete, class: "#{delete_xs} entity-page-xhr"
        td
          = manager.first_name
        td
          = manager.last_name
        td
          = manager.email
        td
          = manager.phone1

app/views/entities/llc/_members.html.slim
= hidden_field_tag :int_action, 'Members List'
.clearfix
table#data_table
  thead
    tr
      th
        | Actions
      th
        | Entity Name
      th
        | Type
      th
        | Contact First Name
      th
        | Contact Last Name
      th
        | EIN / Social
      th
        | Client?
      th
        | Phone
      th
        | Email
      th
        | Membership Interest
  tbody data-active-id=@activeId
    - @members.each do |member|
      - entity_flag = member.entity.present?
      - person_flag = true
      tr data-id=member.id
        td.actions
          = link_to 'Edit', entities_llc_member_path( @entity.key, member.id ), class: "#{edit_xs} entity-page-xhr"
          = link_to 'Delete', entities_llc_member_path( member.id ), data: {:confirm => 'Are you sure?'}, :method => :delete, class: "#{delete_xs} entity-page-xhr"
        td
          - if !member.is_person?
            - person_flag = false
            - if entity_flag
              = link_to member.entity.try(:name), edit_entity_path(member.entity.key)
            - else
              = link_to member.contact.try(:name), edit_contact_path(member.contact)
        td
          - if entity_flag
            = MemberType.member_types[member.member_type_id]
          - else
            = member.contact.role
        td
          - if person_flag
            - if member.entity.present?
              = link_to member.first_name, edit_entity_path(member.entity.key)
            - elsif member.contact.present?
              = link_to member.first_name, edit_contact_path(member.contact)
          - else
            = member.first_name
        td
          = member.last_name
        td
          = member.ein_or_ssn
        td
          - if member.contact_id.nil?
              = 'Yes'
          - else
              = 'No'
        td
          = member.phone1
        td
          = member.email
        td
          = member.my_percentage

app/views/entities/llc/basic_info.html.slim
- if request.xhr?
  == render partial: "entities/llc/basic_info"
- else
  .corporate-forms
    == render partial: "entities/llc/links"
    .clearfix
    .corporate-contact-form
      == render partial: "entities/llc/basic_info"